const featuredProjects = [
  {
    id: 'wargames',
    title: 'wargames',
    url: '/videos/wargames.mp4',
    imageUrl: '/img/wargames-fallback.webp',
    ratio: 1.88,
    route: '/projects/wargames',
    body: 'Wargames is a participatory Generative Art project where Wargames token holders are able to interact with an algorithm and co-create outputs that will belong to the Wargames Generative Collection. In addition, token holders will be able to create their own collections.',
  },
  {
    id: 'alumni-vis',
    title: 'alumni vis',
    url: '/videos/alumni.mp4',
    imageUrl: '/img/alumni-fallback.webp',
    ratio: 0.968,
    route: '/projects/uai-alumni-vis',
    body: "Design and Development of a data visualization and analysis tool for the Adolfo Ibáñez University's Design Faculty ALUMNI survey, designed to graphically display information and enable data disaggregation and correlation, facilitating detailed and comprehensive analysis.",
  },
  {
    id: 'solids',
    title: 'solids',
    url: '/videos/solids-ui-compressed.mp4',
    imageUrl: '/img/solids-fallback.webp',
    ratio: 1.6,
    route: '/projects/solids',
    body: 'Website for the —decentralised— commercialisation of Solids, a generative architecture project created by FAR',
  },
  {
    id: 'teapot',
    title: 'UTAH’S ODISSEY',
    url: '/videos/teapot-5-comp.mp4',
    imageUrl: '/img/teapot-fallback.webp',
    ratio: 1,
    route: '/projects/solids',
  },
]

const otherProjects = [
  {
    id: 'Quasars',
    name: 'QUASARS',
    endClient: 'QUANTUM ART',
    workingFor: 'FINE DIGITAL',
    roles: 'FRONT-END/DESIGNER',
    year: 2022,
    tools: ['React.js', 'Three.js', 'R3F', 'Sass', 'Web3.js', 'Typescript'],
    body: 'Design and development of an interactive digital space (Metaverse) for the exhibition of various digital artworks and photographs offered in auction by the company.',
  },
  {
    id: 'fine',
    name: 'FINE DIGITAL',
    endClient: 'FINE DIGITAL',
    workingFor: 'FINE DIGITAL',
    roles: 'FULL-STACK/DESIGNER',
    year: 2021,
    tools: ['Next.js', 'Three.js', 'Sass', 'Web3.js', 'Typescript', 'Sanity.io'],
    body: 'pending',
  },
  {
    id: 'TEGRA118',
    name: 'TEGRA118',
    body: 'Cloud marketplace for asset managers and traders. It provides them with portfolio management and trading capabilities. The platform provides a dynamic subdomain service for each entity and specific layouts for each user role.',
    endClient: 'jigsaw.xyz',
    workingFor: 'StudioGraphene',
    roles: 'FRONT-END',
    year: 2021,
    web: 'https://www.tegra118.com/',
    tools: ['React.js', 'Redux', 'Typescript', 'AWS Cognito', 'Styled Components', 'Material UI', 'Cypress', 'Jest'],
  },
  {
    id: 'Winnibook',
    name: 'WINNIBOOK',
    workingFor: 'independent',
    body: 'Manitoba’s (Canada) directory of local businesses. It seeks to increase local business visibility through an online directory and blog posts about them, powered by a custom search engine',
    endClient: 'WINNIBOOK',
    roles: 'FRONT-END/DESIGNER',
    year: 2021,
    tools: ['Next.js', 'Tailwind CSS', 'GraphQL'],
  },
  {
    id: 'HELLOSOLO',
    name: 'HELLOSOLO',
    body: 'Platform that allows users to browse and purchase tickets to dating events. Users who attend can then match with other users and start communicating through the platform. Organisations can create accounts to host and manage their own events.',
    endClient: 'hellosolo',
    workingFor: 'StudioGraphene',
    roles: 'FRONT-END',
    year: 2020,
    tools: ['Nuxt.js', 'Vue.js', 'Sass', 'Stripe'],
    web: 'https://www.hatch.global/',
  },
  {
    id: 'Hatch',
    name: 'HATCH AND CREATE',
    body: 'Web application for developing and managing design cases for various products that are sold internally through Hatch, Shopify or Etsy platform. It also has a community section that it’s handled through drupal.',
    endClient: 'Fine Digital',
    workingFor: 'StudioGraphene',
    roles: 'FRONT-END',
    year: 2020,
    tools: ['React.js', 'Sass', 'Redux', 'Stripe'],
    web: 'https://www.hatch.global/',
  },
  {
    id: 'GOLEARN',
    name: 'GOLEARN',
    body: 'AI intervention and assessment platform to help improve the English literacy and learning outcomes of students. It provides a diverse range of exercises, follow up tools and a class based system for teachers and schools.',
    endClient: 'Golearn',
    workingFor: 'StudioGraphene',
    roles: 'FRONT-END',
    year: 2020,
    tools: ['React.js', 'Sass', 'Redux'],
    web: 'https://portal.golearn.guru/login',
  },
  {
    id: 'Extrai',
    name: 'EXTRAI',
    body: 'Design of the visual identity for the EXTRAI Art Festival in Lousal, Portugal, in collaboration with a collective of freelance designers. My role involved creating graphic pieces, developing the website, and producing interactive 3D graphics.',
    endClient: 'Extrai Art Festival',
    workingFor: 'Independent',
    roles: 'FRONT-END/DESIGNER',
    year: 2019,
    tools: ['Gatsby.js', 'Styled Components'],
    web: 'https://www.hatch.global/',
  },
  {
    id: 'Post-ism',
    name: 'POST-ISM',
    body: 'Website for the Post-ism design exhibition, featuring projects developed during the course of the Master’s Degree in Communication Design (Fine Arts, ULisboa), addressing contemporary methods of communication, production, and dissemination of knowledge.',
    endClient: 'Extrai Art Festival',
    workingFor: 'Independent',
    roles: 'FRONT-END/DESIGNER',
    year: 2019,
    tools: ['Vanilla js', 'Three.js'],
    web: 'https://post-ism.fbaul-dcnm.pt/',
  },
]

export { featuredProjects, otherProjects }
