'use client'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 face.glb -T -S -S -d 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { easing } from 'maath'
import { useFrame } from '@react-three/fiber'
import { degToRad } from 'three/src/math/MathUtils'

const Face = (props) => {
  const ref = useRef(null)
  const { nodes, materials } = useGLTF('/face-transformed.glb')

  useFrame((state, delta) => {
    if (!ref.current) return
    ref.current.rotation.y += delta * 0.5
  })

  return (
    <>
      <group ref={ref} {...props} dispose={null} rotation-x={degToRad(-30)}>
        <mesh
          geometry={nodes['aldo-v6'].geometry}
          material={materials['Default OBJ.001']}
          position={[0.316, 0.602, -0.09]}
          rotation={[1.329, 0.002, 1.296]}
          scale={0.07}
        />
      </group>
      {/* <ambientLight /> */}
      <pointLight position={[20, 30, 10]} intensity={0.3} color='blue' decay={0.2} />
      <pointLight position={[-10, -10, -10]} decay={0.2} color='#CCFF00' />
    </>
  )
}

Face.displayName = 'Face'

export { Face }
